### ISSUE TITLE
Implementation

### ISSUE THREAD

**Issue by jomariabejo** [jomariabejo/payroll#13]
# Database Implementation (8/8)
- [x] Create Database
- [x] Create Tables based on scheme diagram of IM
- [x] Create Insert Queries for each table
- [x] Create Update Queries for each table
- [x] Create Read Queries for each table
- [x] Create Delete Queries for each table
- [x] Verify Data Types
- [x] Create Virtual Table

# Desktop Application Implementation

### Employee Access Level (5/7)
- [x] Can view own personal information, salary structure and allowance
- [x] Can view own timesheet records
- [x] Can set time in
- [x] Can set time out
- [x] Can submit leave request if the employee has leave credits left
- [x] Can view their own leave requests
- [x] Can view their own payslip

### HR Admin Access Level (7/8)

- [x] Can view employees
- [x] Can add new employee
- [x] Can update employee
- [x] Can set employee to inactive(NOTE: we will not delete the employee record)
- [x] Can set employee back to active state
- [x] Can view leave requests
- [x] Can approve leave requests
- [x] Can disapprove leave requests

### Payroll Admin Access Level (1/3)
- [x] Has Payroll Dashboard
- [x] Payslips can be generated based on the start and finish of the pay period (Note: Our system suggests generating payslips at the start and end of each month).
- [x] Can view payslips by start pay period and end pay period

### System Administrator Access Level (0/2)
- [x] Can create new user
- [x] Can view users

**Comment by Jasmin172002** [comment]
Class Diagram: https://lucid.app/lucidchart/0873b5c2-18d2-422f-824f-fb9d63a81a78/edit?viewport_loc=1321%2C4591%2C6447%2C3161%2CWRpIK60owzK3&invitationId=inv_fa4752f2-a36f-44a6-b513-a5eaa44d41df
